/*
 * UMSBB Build Configuration
 * Auto-generated by UMSBBCoreBuilder
 */

#ifndef UMSBB_BUILD_CONFIG_H
#define UMSBB_BUILD_CONFIG_H

// Feature flags
#define UMSBB_PERFORMANCE_TESTING 1
#define UMSBB_DETAILED_STATISTICS 1
#define UMSBB_ERROR_CHECKING 1
#define UMSBB_MEMORY_DEBUGGING 0
#define UMSBB_CUSTOM_ALLOCATORS 0
#define UMSBB_NETWORK_SUPPORT 0
#define UMSBB_COMPRESSION 0
#define UMSBB_ENCRYPTION 0

// Build configuration
#define UMSBB_OPTIMIZATION_LEVEL 3
#define UMSBB_TARGET_PLATFORM "wasm"

// Conditional includes based on features
#define UMSBB_INCLUDE_BENCHMARKS

#endif /* UMSBB_BUILD_CONFIG_H */
